--Copyright (c) 2025, Key
--All rights reserved.

--Redistribution and use in source and binary forms, with or without
--modification, are permitted provided that the following conditions are met:

--    * Redistributions of source code must retain the above copyright
--      notice, this list of conditions and the following disclaimer.
--    * Redistributions in binary form must reproduce the above copyright
--      notice, this list of conditions and the following disclaimer in the
--      documentation and/or other materials provided with the distribution.
--    * Neither the name of VanaFacts nor the
--      names of its contributors may be used to endorse or promote products
--      derived from this software without specific prior written permission.

--THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
--ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
--WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
--DISCLAIMED. IN NO EVENT SHALL Key BE LIABLE FOR ANY
--DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
--(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
--LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
--ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
--(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
--SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

_addon.name = 'VanaFacts'
_addon.version = '1.4.1'
_addon.author = 'Key (Keylesta@Valefor)'
_addon.commands = {'vanafacts','vf'}

config = require('config')
texts = require('texts')
require 'chat'
math.randomseed(os.time())

--[[
--Sources--

Timeline lore:
Credit to Elmer the Pointy for translation from various guides
https://ffxi.allakhazam.com/wiki/Bastok_Timeline
https://ffxi.allakhazam.com/wiki/San_d'Oria_Timeline
https://ffxi.allakhazam.com/wiki/Windurst_Timeline
The above was also reposted to FFXIAH for preservation by RadialArcana:
https://www.ffxiah.com/forum/topic/56500/bastok-timeline-by-elmer-the-pointy/
https://www.ffxiah.com/forum/topic/56499/san-doria-timeline-by-elmer-the-pointy/
https://www.ffxiah.com/forum/topic/56498/windurst-timeline-by-elmer-the-pointy/
Various pages from the Fandom FFXI Wiki
https://finalfantasy.fandom.com/wiki/Category:Final_Fantasy_XI
Various pages from BG-WIKI
https://www.bg-wiki.com/ffxi/Main_Page
]]

defaults = {}
defaults.facts = {
	"Approx. 190 CE - The Elvaan establish a settlement in the northern part of the Quon continent.",
	"Approx. 200 CE - The Tarutaru come to Mindartia and settle on the plains of Sarutabaruta.",
	"Approx. 200 CE - The Elvaan split into tribes: Galleon, Fauchevelle, Bulletoran, San d'Oria, Coumlaud and Chatiffe.",
	"217 CE - A village is built around some ancient ruins and named Windurst.",
	"219 CE - A young Tarutaru female named Rimilala discovers magic and is made Windurst's first Star Sybil.",
	"220 CE - Windurst's Star Sybil Rimilala calms the great beast and subdues it in the Full Moon Fountain.",
	"Approx. 220 CE - Galka migrate to their new home, Gustaberg, after the Antica drive them out of their home island of Zepwell.",
	"289 CE - Windurst's Star Sybil Tabiroro summons the various Tarutaru chieftains and teaches them the ways of Magic.",
	"291 CE - The Quadav invade present day Derfland, capturing Pashhow Marshlands.",
	"294 CE - The various Tarutaru tribes join to form The Federation of Windurst.",
	"294 CE - The Parliament of Patriarchs establishes the Mumu as the Federation of Windurst's official currency.",
	"301 CE - The Quadav begin construction of Beadeaux.",
	"311 CE - The Patriarch Protectors are established.",
	"328 CE - Construction of Heavens Tower is completed after 27 years.",
	"332 CE - Soldiers from each Tarutaru clan are split off and reformed into the War Warlocks.",
	"334 CE - Windurst's Star Sybil Shanriri determines that this is the year 334 on the Crystal Era calendar.",
	"336 CE - Negotiations between Windurst and the Yagudo natives breakdown, and both factions become enemies.",
	"337 CE - The War Warlocks invade the native Yagudo's city of Oztroja, forcing them to surrender.",
	"342 CE - The War Warlocks cross the Strait of Jeuno to capture Norvallen.",
	"343 CE - The Galleon tribe of Elvaan are powerless against the magic of Windurst and pledge allegiance to the Federation.",
	"347 CE - Norvallen is declared part of the Federation of Windurst. Young Elvaan are employed as mercenaries.",
	"355 CE - The Yagudo construct Castle Oztroja.",
	"358 CE - The War Warlocks siege Castle Oztroja over two years, but the Yagudo manage to hold them back.",
	"360 CE - A tree growing beside Heaven's Tower has a sudden growth spurt, bursting through parts of the tower.",
	"361 CE - Windurst's Star Sybil Deboruru names the tree that grew into Heaven's Tower the Great Star Tree, and orders its protection.",
	"368 CE - Master Caster Lungo-Nango is selected as chief of Windurst's Norvallen territory.",
	"369 CE - Lungo-Nungo forms the first Elvaan Subjugation Force to control the Elvaan.",
	"370 CE - Windurst, led by Lungo-Nango, invades Ronfaure and overthrows the San d'Oria clan of Elvaan.",
	"371 CE - Lungo-Nango invades Zulkheim, defeating the combined forces of the Fauchevelle, Bulletoran, and San d'Orian tribes.",
	"372 CE - Lungo-Nango is designated Warlock Warlord.",
	"372 CE - Lungo-Nango invades Gustaberg. The mountain-dwelling Chatiffe tribe battle against them using guerilla tactics.",
	"373 CE - The last fortification of the Elvaan Chatiffe tribe, Fort Morteuge, falls to Windurst.",
	"374 CE - Ronfaure and Zulkheim become official territories of Windurst.",
	"374 CE - Lanfeaur d'Oraguille, a young San d'Orian boy, learns the ways of the Dragoon.",
	"375 CE - Lungo-Nango appears before the Parliament of Patriarchs and is removed from the position of Warlock Warlord.",
	"375 CE - Parliament member Atogi-Nokutogi is selected to replace Lungo-Nango as Warlock Warlord.",
	"375 CE - Wellpard, a young boy of the Elvaan Bulletoran tribe, invents saddles and reins to use chocobos as mounts.",
	"376 CE - Lanfeaur is selected to be the head of the San d'Oria tribe.",
	"377 CE - Lanfeaur leads a unit of young men in an assault on Ronfaure, then held by Windurst, and occupies the territory.",
	"378 CE - On the orders of Windurst, Galleon and Bulletoran Elvaan invade Ronfaure, but are pushed back by the San d'Orians.",
	"379 CE - The young Arefeauron Tavnazia, of the Bulletoran tribe, joins forces with d'Oraguille.",
	"380 CE - The San'Orian Elvaan retake control of Zulkheim from the Bulletoran and Fauchevelle tribes, who are controlled by Windurst.",
	"381 CE - Lanfeaur of the San d'Orian tribe meets with the Quadav King and forms an alliance against Windurst.",
	"382 CE - The San d'Orian tribe and the Quadav ambush the Windurst army in Jugner Forest and Pashhow Marshlands, driving them back.",
	"382 CE - The allied forces of Elvaan and Quadav defeat Warlock Warlord Atogi-Nokutogi and the second Elvaan Subjugation Force.",
	"383 CE - Arefeauron of Tavnazia meets with the mountain-dwelling Chatiffe tribe, convincing them to ally with the San d'Orian tribe.",
	"385 CE - The Kingdom of San d'Oria is founded.",
	"385 CE - The retainer Arefeauron (founding Marquis of Tavnazia) is assigned to the Western peninsula of Quon.",
	"387 CE - The Kingdom of San d'Oria conforms all currency under the unit Noit.",
	"376 CE - While under house arrest in Mhaura, Lungo-Nango dies suddenly of a fever, and is thought to be an assassination.",
	"388 CE - The Marquis of Tavnazia, Arefeauron, dies.",
	"390 CE - To facilitate the minting of currency, San d'Oria establishes a Blacksmith's Guild.",
	"391 CE - The Royal Knights are formed with Fainevlure Ordelle appointed as their first captain.",
	"398 CE - Samariri, a TaruTaru peace officer, teaches the Elvaan the ways of Magic.",
	"399 CE - The Elvaan invade Norvallen. Warlock Warlord Dakaru-Jinkaru and six units of War Warlocks are defeated at Fort Jabigogo.",
	"401 CE - San d'Orian King Lanfeaur's cousin, Phulmvonne Shahkam, receives jurisdiction over Norvallen.",
	"403 CE - Construction of Castle D'Oraguille is completed.",
	"410 CE - The Kingdom of San d'Oria officially recognizes the Goddess Altana.",
	"413 CE - A non-aggression pact between San d'Oria and Windurst is signed.",
	"413 CE - The Marquisate of Tavnazia is founded as an independent state.",
	"414 CE - As a result of cultural exchanges with Windurst, San d'Oria adopts the use of the Crystal Era calendar.",
	"418 CE - Gold is discovered in Gusgen Mines.",
	"420 CE - San d'Oria violates the non-aggression pact with Windurst, invading Mindartia and setting up a fort in Sauromugue.",
	"420 CE - A gold rush erupts in the Gusgen Mountains, resulting in an influx of Hume settlers in the area.",
	"421 CE - San d'Oria's Ironblood King Lanfeaur passes away in camp.",
	"421 CE - Lanfeaur's third son, Resviel, is crowned the \"King of Hope\", as San d'Oria's second ruler.",
	"423 CE - The War Warlocks activate a plan to destroy San d'Oria's capital, wreaking havok within the city.",
	"424 CE - The Temple Knights are formed after the War Warlocks wreak havoc in the San d'Orian capital.",
	"441 CE - A Yagudo called Lehh Habro appears, claiming to be the manifestation of god, and quickly gains a devout following.",
	"456 CE - A gold rush causes an influx of Hume miners in the Kingdom of San d'Oria's capitol.",
	"457 CE - Windurst forms a Leathercrafting Guild after a surge in Mithra hunters causes a surplus of animal pelts.",
	"458 CE - The Temple Knights banish all Hume from the Kingdom of San d'Oria.",
	"460 CE - For their achievements in upholding public order, The Temple Knights are recognized as an official branch of the military.",
	"463 CE - The Royal Knights attack a settlement of Hume and Galka miners.",
	"466 CE - San d'Oria's forces flee from a mere trio of Combat Casters, abandoning their last fort on Mindartia continent.",
	"469 CE - To ensure the safety of miners, Ironman Mayer plans the construction of a fort in the valleys of Bastok.",
	"474 CE - San d'Oria forms a Woodworking guild to supply weapons for the army and support an unprecedented boom of development.",
	"477 CE - Galkan blacksmiths develop the process of refining Mythril.",
	"482 CE - Lehh Habro organizes the devout Yagudo into a theocracy.",
	"485 CE - San d'Oria holds a grand festival for its 100th anniversary.",
	"487 CE - The Sand'Orian army invades the valleys of Bastok and were soundly defeated.",
	"487 CE - Ironman Mayer's reputation is boosted immensely with the Bastokan forces victory over the feared Royal Knights of San d'Oria.",
	"487 CE - Windurst's library is officially titled the Opistery. Parliament member Marokuku is inducted as the first director.",
	"489 CE - Baron Gheorlmitt Phern plots with the Queen to overthrow the San d'Orian royal family.",
	"491 CE - Fort Bastok is completed.",
	"491 CE - San d'Oria holds a parade for the 100th anniversary of the formation of The Royal Knights.",
	"493 CE - Lehh Habro establishes the Yagudo Theomilitary.",
	"494 CE - The Republic of Bastok is formed with Ironman Mayer as it's first president.",
	"494 CE - Bastok's Ministry of Domestic Affairs is established. The first Minister, Balz, is inaugurated.",
	"494 CE - Bastok's Ministry of Foreign Affairs is established. The first Minister, President Mayer, is inaugurated.",
	"495 CE - Bastok's Department of Defense is established with the Galka, Dalha, inducted as the first Commander.",
	"496 CE - Bastok's Department of Mining is established with Falk inducted as the Head Foreman.",
	"497 CE - The Republic of Bastok's constitution is created.",
	"498 CE - Bastok's President Mayer dispatches a delegate to the Near East to establish diplomatic relations.",
	"500 CE - An army of Yagudo, led by Lehh Habro, invades Sarutabaruta.",
	"500 CE - Kontsu-Orontsu defeats Lehh Habro and the Yagudo army with Flare, a unique Black Magic spell of his own design.",
	"502 CE - The Yagudo theocracy learns magic from their Tarutaru prisoners.",
	"503 CE - President Mayer is assassinated by a Galkan youth. Vice President Elman is inaugurated as Bastok's second President.",
	"508 CE - A Mythril seam is discovered in Gusgen Mines.",
	"509 CE - Windurst's public magic training grounds are officially titled the Orastery. Kontsu-Orontsu is inducted as the first director.",
	"526 CE - A Leathercrafting guild is established after leather becomes fashionable amongst the aristocracy and the royal family.",
	"527 CE - Bastok's Department of Commerce is established, with Darell inducted as head.",
	"527 CE - Bastok's Department of Commerce developed the Byne, a unit of currency to be used among the Hume and Galka.",
	"528 CE - A Mint is made under the direction of Bastok's Department of Commerce.",
	"529 CE - To facilitate the minting of coins and export of gemstones, Bastok orders the creation of a Goldsmithing guild.",
	"534 CE - The Yagudo Theomilitary invade Windurst but are driven off by Gurebu-Ogurebu and his sister, the Silent Mage Medada.",
	"536 CE - Windurst's College of Magic is officially titled the Aurastery. Gurebu-Orgurebu is inducted as the first director.",
	"538 CE - San d'Oria's King Charambille passes away.",
	"538 CE - Construction of the Phanauet Channel is completed after 35 years.",
	"542 CE - Construction of the San d'Orian Cathedral is completed after 120 years.",
	"548 CE - Windurst's pharmaceutical research facility is officially titled the Rhinostery. Its first director is the White Mage Guribubu.",
	"549 CE - Bastok orders the creation of a Blacksmithing guild to teach Galka and Hume metallurgists secret metal-crafting techniques.",
	"558 CE - The Warking Acheufagais ascends to the throne.",
	"559 CE - The Orcish Imperial Army lands on the northern shores of Quon.",
	"561 CE - San d'Oria's King Acheufagais defeats 1,000 Orcs with brutal force.",
	"563 CE - The Warking Acheufagais and his party attack and are repelled from the Konschtat Highlands.",
	"563 CE - Medada invents the Linkshell (though not as powerful as today's models).",
	"564 CE - Victory Arch is completed in honor of King Acheufagais.",
	"565 CE - Bastok's Republican Legion adds a second faction.",
	"567 CE - San d'Oria's King Acheufagais dies due to complications from wounds suffered in battle.",
	"568 CE - King Acheufagais's cousin, Marelinne, is made Queen of San d'Oria after his death.",
	"572 CE - Knights from San d'Oria cross the Strait of Jeuno and attack a Federation fort but are repelled by the War Warlocks.",
	"574 CE - Windurst's magical weapons plant is officially titled the Manustery. Medada is inducted as the first director.",
	"577 CE - Bastok's chapel is built.",
	"580 CE - Queen Marelinne marries Count Phildenan of Tavnazia.",
	"586 CE - Queen Marelinne's troupe shipwrecks against the Ashak Mountains. The search is called off after 2 years.",
	"588 CE - Hunterking Dormillique ascends to San d'Oria's throne.",
	"588 CE - A party of envoys from the East visit Windurst. They are denied an audience with the Star Sybil for being heretics.",
	"589 CE - A party of envoys from the East establishes diplomatic relations with the Yagudo Theocracy.",
	"589 CE - The Yagudo begin regularly receiving weaponryand instruction in the Eastern arts, such as Ninjutsu, from the East.",
	"594 CE - Bastok holds a grand festival for its 100th anniversary.",
	"594 CE - The place where Ironman Mayer first broke ground with his pickaxe in Bastok is christened \"Firewater Circle.\"",
	"595 CE - Bastok's Department of Industry is established, with Lilienthal as its head.",
	"599 CE - Windurst's Star Sybil Seboriri is dispatched to the South as an representative of Windurst.",
	"604 CE - San d'Oria's King Dormillique restricts hunting in the woods of East Ronfaure to the royal family.",
	"606 CE - The Bonecrafting Guild is established in Windurst as a result of learning new crafting techniques from the South.",
	"607 CE - Sheep are brought over from islands in the West and begin grazing in Zulkheim.",
	"611 CE - Gunpowder is invented in Bastok by Conrad, an alchemist.",
	"625 CE - The Parliament of Patriarchs creates the official flag of the Federation of Windurst.",
	"626 CE - San d'Oria holds an international swordsman tournament. The winner is Grand Knight Silvelliffe.",
	"627 CE - A Galka metallurgist in Bastok develops the \"cannon,\" through study of a shipwreck in the Near East.",
	"630 CE - Ballista is developed in the woods of Ronfaure.",
	"641 CE - San d'Oria's King Dormillique passes away.",
	"642 CE - Using secret Eastern techniques, a Yagudo suicide squad invades the Parliament's conference hall and destroy it.",
	"644 CE - Bastok's Gunpowder Room is created, with Degsha inducted as the lead researcher.",
	"650 CE - Bastok's Iron Musketeers are established under the Department of Industry, with Schultz inducted as its first commander.",
	"658 CE - Bastok's Ministry of Domestic Affairs invites Sechil-Puchil, a famous astronomer from Windurst.",
	"658 CE - Bastok's President Arens adopts Windurst's Crystal Era calendar, phasing out the old, Altepa-based calendar.",
	"659 CE - Bastok's President Arens renounces his position and proposes the idea of a national election, which is accepted by the people.",
	"659 CE - Mhaura becomes an officially governed territory of Windurst.",
	"663 CE - The Orcish Imperial Army tunnels through the northern mountains and attacks Norvallen.",
	"664 CE - The supply of Mythril in Gusgen Mines is exhausted.",
	"665 CE - Lord Falledemion is recognized as a great hero, and his image is carved into Victory Arch.",
	"676 CE - The Black Mage Toraimarai investigates the large canals sealed underneath the capital.",
	"679 CE - Construction begins on the windmills of Konschtat Highlands.",
	"681 CE - Bastok's Gold Musketeers are created under the Department of Mining, with Friese inducted as their first commander.",
	"682 CE - Bastok's Republican Legion adds a naval faction.",
	"682 CE - Cultivation of Uragnites begins in Bibiki Bay.",
	"684 CE - The Gold Musketeers discover a Mythril seam around a Quadav settlement in the Palborough Mountains.",
	"685 CE - Bastok's Republican Legion swiftly strikes against the Quadav, wiping them out.",
	"686 CE - Wolfking Raigegue ascends to San d'Oria's throne.",
	"687 CE - Bastok's Mythril Musketeers, an elite unit under the direct control of the President, is formed.",
	"690 CE - San d'Oria's King Raigegue leads The Royal Knights on an invasion of Gustaberg.",
	"691 CE - Bastok's Republican Legion clashes with San d'Orian forces in Konschtat Highlands. Bastok attains a decisive victory.",
	"692 CE - Bastok's Republican Legion expands into another faction and establishes of the Four Republican Legions.",
	"693 CE - San d'Oria's Prince Ferrenan takes advantage of King Raigegue's absence and attempts to gain control over the capitol.",
	"697 CE - A large scale war breaks out against beastmen in the Southern lands.",
	"697 CE - The Parliament of Patriarchs dispatches two units of War Warlocks to help in the battles in the Southern lands.",
	"697 CE - Missionaries from the East teach the friars of Bastok various aspects of their arts and culture.",
	"701 CE - Construction of the Bostaunieux Oubliette is completed after 7 years.",
	"702 CE - San d'Oria's Prince Ferrenan proclaims himself King. The Era of Two Kings Begins.",
	"703 CE - Morhen Lighthouse is constructed.",
	"704 CE - A party of envoys from the East meet with Windurst's Star Sybil Rakapopo and diplomatic relations are established.",
	"711 CE - Blotches begin to appear all over the bodies of Humes, signaling the beginning of a deadly plague, The Bastokan Blight.",
	"716 CE - A cure for the plague, The Bastokan Blight, is developed.",
	"717 CE - The Clothcrafting guild is formed in Windurst to prepare for the coming Great Festival of Magic and control costs.",
	"719 CE - The Great Festival of Magic in Windurst celebrates the 500th anniversary of the discovery of magic.",
	"720 CE - The plague, the Bastokan Blight, is almost completely wiped out.",
	"720 CE - The cultivation of Rolanberries becomes very popular around the outskirts of Jeuno.",
	"727 CE - A new type of gunpowder, \"Dancing Flames,\" is utilized in the excavation of Palborough Mountain.",
	"730 CE - Fort Bastok is converted into the Metalworks.",
	"748 CE - The adventurer Gwynham Ironheart sets off on his journey to map the world.",
	"755 CE - The Fishing guild is established in Windurst to settle disputes and help improve the lives of all fishermen.",
	"761 CE - The Orcish Empire of Quon sends an advance party to invade Ronfaure.",
	"762 CE - The adventurer Gwynham Ironheart discovers an inlet in Valkurm Dunes, and names it Selbina.",
	"768 CE - Baron Torresapet Ordelle is sent to inspect limestone caverns in La Theine Plateau, known today as Ordelle's Caves.",
	"769 CE - Construction begins on the port town, Selbina.",
	"769 CE - The Mithra Marines are formed as a countermeasure to the meddlesome Mithra pirates.",
	"772 CE - Bastok President Ritter is inaugurated, and the current Republic Flag is created.",
	"778 CE - Enid, a traveler from San d'Oria, receives an audience with Windurst's Star Sybil Kofufu.",
	"782 CE - Dragonking Ranperre is crowned San d'Oria's King.",
	"783 CE - San d'Oria's King Ranperre is bestowed with a holy sword from the North.",
	"786 CE - Bastok and Tavnazia's combined naval forces battle against the Windurst navy near Elshimo Island.",
	"795 CE - The War Warlocks increase their size from 9 factions to 12.",
	"796 CE - The Quadav select Za'Dha as Adamantking.",
	"800 CE - Bastok's Department of Commerce introduces paper money.",
	"811 CE - Bastok's Ministry of Domestic Affairs is merged into the Department of Industry.",
	"811 CE - Bastok's Ministry of Foreign Affairs is merged into the Department of Commerce.",
	"812 CE - The Yagudo army invades West Sarutabaruta, taking out the War Warlocks and Mithra Marines.",
	"815 CE - King Ranperre gains victory over King Gjohnberre, once again uniting San d'Oria under a single monarchy.",
	"815 CE - Extensions are built on to the Metalworks in Bastok, and the chapel is dismantled and relocated.",
	"816 CE - The school of Dragoons cease to exist.",
	"816 CE - The Yagudo Theocracy names their captured Sarutabaruta territory Giddeus and members begin to immigrate.",
	"817 CE - Volledyne is made Count and assigned to Jugner Forest.",
	"817 CE - King Ranperre creates the official San d'Orian flag.",
	"824 CE - Mithra visiting Windurst from the South teach the ways of the Beastmaster.",
	"824 CE - The current king of San d'Oria, King Destin, is born.",
	"828 CE - The Bastokan President's office is moved to the top of the Metalworks.",
	"830 CE - San d'Oria's King Ranperre exterminates the black dragon, Vrtra. He is awarded the title of \"Dragonking\" for his victory.",
	"831 CE - Construction of San d'Oria's King Ranperres Tomb is completed. The black dragon Vrtra is sealed within.",
	"832 CE - San d'Oria's King Ranperre passes away.",
	"832 CE - San d'Oria's King Grantieul ascends to the throne.",
	"833 CE - Cid is born",
	"835 CE - The Summoner Karaha-Baruha is born.",
	"835 CE - A project to employ Bastok's out-of-work masons and secure land trade routes starts in Jeuno, then just a small fishing village.",
	"836 CE - Due to an accidental explosion, the Alchemy guild in Bastok is transferred to Ore Street.",
	"839 CE - The Beastmaster Tah Palancha domesticates Dhalmels.",
	"843 CE - Baron Periduke is inaugurated as Prime Minister of San d'Oria.",
	"845 CE - In order to repair the royal family's financial state, Prime Minister Periduke outlines a plan for economic reform.",
	"849 CE - The Gusgen Mines experience a massive cave-in and is engulfed in flames.",
	"850 CE - Marquis Rochefogne of Tavnazia is born.",
	"851 CE - San d'Oria's King Grantieul is ambushed and killed by Orcs. The Crown Prince Destin barely escapes with his life.",
	"851 CE - Destin ascends to the San d'Orian throne, considered a temporary placeholder due to the previous King's sudden demise.",
	"851 CE - The Gusgen Mines are closed.",
	"853 CE - San d'Oria's King Destin marries Countess Leaute of Tavnazia.",
	"854 CE - A Multinational Expedition team explores the Northlands, with Mythril Musketeer Raogrimm as their leader.",
	"855 CE - Reports from the Multinational Expedition cease as rumors of a \"Shadow Lord\" begin to circulate.",
	"855 CE - Crystal synthesis is introduced by Kam'lanaut when he comes to Jeuno.",
	"856 CE - Karuha-Baruha begins his research on Summoning Magic.",
	"856 CE - Cid launches new technologically advanced ships of his own design.",
	"856 CE - Cid is made lead engineer of the Metalworks.",
	"857 CE - Ferry service between Selbina and Mhaura is established.",
	"858 CE - The Shadow Lord's Army clashes with the Orcish Empire in the Northlands.",
	"858 CE - San d'Oria's Temple Knights and Prime Minister Periduke uncover a plot to assassinate King Destin.",
	"858 CE - A grand coronation ceremony is held for San d'Oria's King Destin. The Papsque bestows Destin with the Crown of the Gryphon.",
	"859 CE - The Grand Duchy of Jeuno is officially recognized as an independent nation.",
	"859 CE - Kam'lanaut, a representative of Jeuno, is awarded the title of Archduke by the three nations.",
	"859 CE - The Yagudo Theocracy submit to the Shadow Lord and are brought under his control.",
	"860 CE - Prince Trion is born.",
	"860 CE - Construction of Castle Zvahl is complete.",
	"861 CE - Cardians are invented.",
	"861 CE - The Shadow Lord gathers the Beastmen leaders at Castle Zvahl and proclaims the destruction of the human nations.",
	"862 CE - Prince Pieuje is born.",
	"862 CE - The Orcish Army storms San d'Oria's capital. After a fierce battle, The Royal Knights manage to repel them.",
	"862 CE - Muchanne, leader of The Temple Knights, is assassinated (prevailing theory is by a Tonberry).",
	"4/862 CE - The Crystal War begins when a mixed army of Beastmen invade Norvallen.",
	"5/862 CE - The Mithra Navy urgently recruits new soldiers and reforms as the Mithra Mercenaries.",
	"6/682 CE - The Sahagin construct a blockade in Port Bastok.",
	"7/862 CE - The Yagudo army invades Windurst's capital. They barely manage to repel the attack, and suffer massive damage in the process.",
	"8/862 CE - Windurst's Parliament of Patriarchs dispatch an envoy to the Southern lands, who send a large number of reinforcements.",
	"8/862 CE - Responding to Eald'narche's summons, President Prien, King Destin, and the Star Sybil travel to Jeuno to meet.",
	"9/862 CE - The Allied Forces of Altana is formed between the 4 nations to counter the Shadow Lord's army.",
	"10/862 CE - Fort Karugo-Narugo is suddenly besieged by a Beastman anti-magic unit.",
	"10/862 CE - The Beastmen army invades the capital of Windurst.",
	"10/862 CE - The Head of Bastok's Military Affairs, Berner, is killed by a Tonberry assassin.",
	"10/862 CE - Cid is given a secondary position as lead researcher of Bastok's Gunpowder Room.",
	"11/862 CE - Karaha-Baruha releases the avatar Fenrir and obliterates the Beastmen army from the capital.",
	"11/862 CE - A unit of Royal Knights arrive at Fort Karugo-Narugo and help Windurst to repel the Beastmen forces.",
	"11/862 CE - The Hydra Corps is formed.",
	"12/862 CE - The Beastmen army's main forces amass around Jeuno.",
	"1/863 CE - Garlaige Citadel is destroyed.",
	"1/863 CE - The Beastmen launch an offensive from the outskirts of Jeuno.",
	"2/863 CE - Due to a lack of soldiers, Cardians are added to the ranks of the War Warlocks.",
	"4/863 CE - The main units of the Allied Forces of Altana gather in Xarcabard, engaging the Beastmen.",
	"7/863 CE - Castle Zvahl is surrounded by the Allied Forces of Altana.",
	"8/863 CE - The Hydra Corps disappear without a trace.",
	"9/863 CE - The Shadow Lord is sealed.",
	"11/863 CE - Castle Oztroja crumbles under an attack from the Mithra Mercenaries.",
	"863 CE - Tavnazia falls to the Shadow Lord's Beastmen Army.",
	"3/864 CE - Representatives of the four nations gather in Jeuno, and the Crystal War is officially proclaimed to be over.",
	"11/864 CE - Windurst Woods is set aside as an autonomous section of Windurst for Mithra to inhabit.",
	"864 CE - Shamonde is inaugurated as Papsque of the San d'Orian cathedral.",
	"864 CE - The Orcish Empire begins withdrawing from the continent of Quon.",
	"865 CE - Jeuno holds a post-war conference. Continuing positive relations between the four nations is unanimously accepted.",
	"865 CE - Obsolete Cardians plan an insurrection.",
	"866 CE - Windurst takes notice of the Yagudo's state of distress and approves a policy of reconciliation.",
	"867 CE - Windurst signs a peace treaty with the Yagudo Theocracy.",
	"867 CE - The Palborough Mines experience a cave-in.",
	"867 CE - Cid resigns as head researcher of Bastok's Gunpowder Room.",
	"868 CE - The Republic of Bastok's monetary unit, the Byne, is abandoned in favor of Jeuno's currency, Gil.",
	"868 CE - The Kingdom of San d'Oria's monetary unit, the Noit, is abandoned in favor of Jeuno's currency, Gil.",
	"868 CE - The Federation of Windurst's monetary unit, the Mumu, is abandoned in favor of Jeuno's currency, Gil.",
	"869 CE - Queen Leaute passes away.",
	"869 CE - The Quadav build a canal off of their sanctuary into Palborough Mines, assaulting and capturing it.",
	"870 CE - To facilitate the work of the various chefs gathering from around the globe, a Cooking guild is established.",
	"871 CE - Tzee Xicu the Manifest is resurrected. The Yagudo Theomilitary begins to mobilize once more.",
	"872 CE - Development begins on Zeruhn Mines.",
	"873 CE - Reports from Cardian scouts indicate the reconstruction of Castle Oztroja.",
	"873 CE - A drawbridge is built over Dalha River.",
	"875 CE - The first Bastok to Jeuno airship flight is launched.",
	"875 CE - The archeologist, Bertolino, discovers the remains of an ancient society in Dangruf Wadi.",
	"875 CE - The Orcs capture La Vaule and rename it Davoi.",
	"876 CE - An observatory is established on top of the Opistery.",
	"877 CE - The first Windurst to Jeuno airship flight is launched.",
	"877 CE - Beastmen activity begins to intensify in several regions. whispers start about the possible return of the Shadow Lord.",
	"878 CE - Improvements to Port San d'Oria begin for the accommodation of airships.",
	"879 CE - Reports of Fort Ghelsba, an Orcish outpost, are confirmed.",
	"881 CE - Airship travel between San d'Oria and Jeuno is established",
	"882 CE - Richter Karst is elected President of Bastok.",
	"882 CE - Edwards, a Hume alchemist, develops Cermet.",
	"883 CE - Kam'lanaut proposes Conquest as a means to ascertain political boundaries.",
	"883 CE - The Orcish Army once again invades Ronfaure, but are repelled by The Royal Knights.",
	"884 CE - Ordinary people called \"Adventurers\" begin appearing in every region, responding to any crisis.",
	"884 CE - The underground Moblin city, Movalpolis, is discovered in Gustaberg.",
	"884 CE - Bastok's Department of Mining approves the reopening of Korroloka Tunnel for adventurers.",
	"The oldest known evidence of a Hume village was found in Dangruf Wadi from 3000 years ago.",
	"The star Gordeus in the Alexander constellation going supernova marks the beginning of the Crystal Era.",
	"In terms of storyline, \"the present\" is considered the year 884 CE, while the start of Rhapsodies of Vana'diel is 898 CE.",
	"The Grandy Duchy of Jeuno is governed by Archduke Kam'lanaut. Due to his busy schedule, however, he is often away from Jeuno.",
	"The Grandy Duchy of Jeuno is suspended on a bridge the connects the Quon and Mindartia continents.",
	"Built on bridges that connect three peninsulas and two continents, it is said that \"all things find their way to Jeuno\".",
	"Selbina was once a prosperous town and a strategic port for the navy of Mindartia and a waypoint for travelers.",
	"Mhaura is carved into the cliffs facing the Strait of Pamtam and is part of the Federation of Windurst.",
	"Moat Carp are a freshwater fish found in lakes and marshes all over Vana'diel.",
	"Fluoro-flora are used in Windurst as street lamps. Originally from Elshimo Island, the Rhinostery enhanced them to shine more intensely.",
	"Humes have the widest spread population as well as the widest variety of names, but do not follow any special rules for their naming.",
	"Elvaan males tend to have elaborate names appropriate for heroes in an epic tale.",
	"Elvaan females typically have shorter names that are easy to pronounce.",
	"Elvaan often just use a first name, but can use a middle initial and last name.",
	"Elvaan middle initials relate to their rank in either the nobility or the clergy.",
	"The Elvaan middle initial 'R', the Nobility rank Royaulais, is for a king or member of the royal family.",
	"The Elvaan middle initial 'I', the Nobility rank Imperiais, is for the founder of a vassal state or descendant from the royal family.",
	"The Elvaan middle initial 'M', the Nobility rank Monarlais, is for the lord of a county.",
	"The Elvaan middle initial 'S', the Nobility rank Souvelais, is for a deputy count.",
	"The Elvaan middle initial 'B', the Nobility rank Barolais, is for a lower-ranked lord.",
	"The Elvaan middle initial 'N', the Nobility rank Noblais, is for an elite fighter worthy of an honorary title.",
	"The Elvaan middle initial 'P', the Clergy rank Papsque, is for a leader of the San d'Orian Cathedral.",
	"The Elvaan middle initial 'C', the Clergy rank Cardisque, is for a chief official of the Cathedral.",
	"The Elvaan middle initial 'E', the Clergy rank Evesque, is for a teaching Leader of the Cathedral.",
	"The Elvaan middle initial 'V', the Clergy rank Vicasque, is for a deputy Bishop.",
	"The Elvaan middle initial 'X', the Clergy rank Croisque, is for an elite Monk deployed by the Cathedral.",
	"Mithra use a first name and family name. First names are short, just one or two syllables.",
	"Galkan names have rough-sounding syllables, often using hard consonants.",
	"Humes find Galkan names hard to remember or pronounce, and usually give them another name.",
	"Male Tarutaru have names where the first and second part rhyme. This is thought to be similar to incantations of ancient spells.",
	"Female Tarutaru have names where the last mora is repeated.",
	"The last part of female Tarutaru names are based on the orientation of the child in relation to the Star Tree at the time of birth.",
	"Male Goblin names end in -ix.",
	"Female Goblin names end in -ox.",
	"An Onze is the equivalent of an Ounce.",
	"A Ponze is the equivalent of a Pound.",
	"An Ilm is the equivalent of an Inch.",
	"A Fulm is the equivalent of a Foot.",
	"A Yalm is the equivalent of a Yard.",
	"A Malm is the equivalent of a Mile.",
	"One Vana'diel minute is 2.4 Earth seconds.",
	"One Vana'diel hour is 2 minutes, 24 seconds Earth time.",
	"One Vana'diel day is 57 minutes, 36 seconds Earth time (1/25 of one Earth day).",
	"One Vana'diel week is 7 hours, 40 minutes, 48 seconds Earth time.",
	"Hitting an upright-walking Gnole with a Silver Arrow or Bullet will revert them back to walking on all fours.",
	"Gnoles walk upright in the daytime during Waxing Gibbous, Full Moon, and Waning Gibbous moon phases.",
	"Ro'Maeve's Qu'Hau Spring and moongates will be activated during a Full Moon between 18:00 and 6:00.",
	"The moon doesn't seem to have been given a name on either Vana'diel or Abyssea.",
	"The moon's color varies based on the current day of the Vana'diel week.",
	"In Abyssea, the moon seen in the night sky appears significantly larger.",
	"Abyssea is an alternate dimension that exists parallel to Vana'diel.",
	"One lunar cycle lasts for 84 in-game days, which is 3 days, 8 hours, 38 minutes, and 24 seconds in Earth time.",
	"The Horutoto Ruins in Sarutabaruta draw on the energies of the moon.",
	"Elemental Ores are obtainable in Chocobo Digging during the Waxing Crescent moon phase.",
	"Magic accuracy is affected by the day of the week.",
	"Daytime runs from 6:00 to 18:00.",
	"Nighttime runs from 18:00 to 6:00.",
	"Dusk runs from 17:00 to 18:00.",
	"Dawn runs from 6:00 to 7:00.",
	"Outside of dungeons, Undead can spawn between 20:00 and 4:00.",
	"Certain Eruca and Karakul sleep for most of the night and are not aggressive during that time.",
	"Ladybugs are only aggressive during the daytime.",
	"Single Fire weather is called Hot Spells.",
	"Double Fire weather is called Heat Waves.",
	"Single Earth weather is called Dust Storms.",
	"Double Earth weather is called Sandstorms.",
	"Single Water weather is called Rain.",
	"Double Water weather is called Squalls.",
	"Single Wind weather is called Winds.",
	"Double Wind weather is called Gales.",
	"Single Ice weather is called Snow.",
	"Double Ice weather is called Blizzards.",
	"Single Thunder weather is called Thunder.",
	"Double Thunder weather is called Thunderstorms.",
	"Single Light weather is called Auroras.",
	"Double Light weather is called Stellar Glare.",
	"Single Dark weather is called Gloom.",
	"Double Dark weather is called Darkness.",
	"Don't forget your family, your friends, your school, or your work.",
	"It all began with a stone, or so the legend says.",
	"You can store the various Seals and Crests with either Shami or Shemo in Port Jeuno.",
	"You can store the various Rem's Tales with Monisette in Port Jeuno.",
	"Porter Moogles found in various towns will store many different items on Storage Slips for you.",
	"Trade an item by itself to a Porter Moogle to check if it can be stored on a Storage Slip.",
	"Sparks NPCs will also store your Copper Vouchers for use with them later.",
	"Divainy-Gamainy at the Inventors' Coalition will store various augmentation stones such as Wailing or Duskdim Stones.",
	"Trade a used Mars or Venus Orb back to Greyson in Lower Jeuno for a chance at receiving a brand new one.",
	"Vana'diel is a name that means \"mother earth\".",
	"Fauregandi means \"frozen earth\" in Old Elvaan.",
	"Sarutabaruta means \"Land of Prophecy\" in the Tarutaru tongue.",
	"Kolshushu means \"Land of Decision\" in the Tarutaru tongue.",
	"Beaucedine Glacier is a harsh land with constant blizzards.",
	"Jugner Forest is a dense woodland often shrouded in darkness--even during the day.",
	"Attohwa means \"arid\' in ancient Mithran, and is the name given to the chasm that traverses the eastern part of Aragoneu.",
	"Little rain falls in Attohwa Chasm, resulting in a parched, broken land where poisonous gases erupt from cracks in the earth.",
	"Until discovery of an underground route, several forbidding cliffs had to be scaled in order to reach Attohwa Chasm.",
	"High atop the mountains of the Aragoneu region, Boneyard Gully is at the peak of Attohwa Chasm.",
	"Boneyard Gully is shielded by a strange dark miasma which seemingly prevents all entry.",
	"The Yagudo spent decades carving Castle Oztroja out of the mountains in the Meriphataud Range.",
	"The interior of the Castle Oztroja is extremely complex and littered with traps and curses.",
	"Located deep within Castle Oztroja, the Altar Room is believed to house the sacred altar of the Yagudo Theocracy.",
	"There are three \"Banishing Gates\" in Garlaige Citadel which must be opened to access certain areas of the zone.",
	"The Meriphataud Mountains of Mindartia is an area of dry and harsh conditions and brutal dust storms.",
	"The gigantic and symbolic Drogaroga's Spine stretches across the Meriphataud Mountains hanging high above the hills.",
	"In the southeast of the Meriphataud Mountains is a large and mysterious crater.",
	"The southern portion of Meriphataud Mountains consists of a low-lying area with untraversable caverns known as Galesmouth.",
	"The single most conspicuous feature in Meriphataud Mountains, Drogaroga's Spine spans most of the area in the air.",
	"The Sauromugue Champaign is on a peninsula that bugles out into the Bastore Sea and the Strait of Jeuno.",
	"Located in the center of Sauromugue Champaign, the Gausebit Mountains jut over the plain.",
	"The Great Jeuno Bridge connects the Quon and Mindartia continents.",
	"Port Jeuno was built upon the Harbor Bridge.",
	"Oggodett, Antonian, and Maqu Molpih will sell items from Aragoneu when their country is in control of the region.",
	"The Arrapago Reef is a highly treacherous area legendary for stranding many a ship.",
	"The Arrapago Reef became the final bastion for a kingdom that was destroyed by an attack from Aht Urhgan.",
	"The Lamiae are currently using the Arrapago Reef as their stronghold, guarded by the sleepless undead.",
	"Caedarva Mire is a vast stretch of swampland covering Azouph Isle, covered in dense fog nearly all year round.",
	"Caedarva means \"illusion\" in the language of Ephramad.",
	"Caedarva Mire is the ancient site of a great battle between the Empire of Aht Urhgan and the Kingdom of Ephramad.",
	"Derfland is a massive peninsula, located on the eastern side of the Quon continent and jetting out into the Bastore Sea.",
	"Beadeaux is located deep within the Pashhow Marshlands, far from the reach of Bastokan and San d'Orian forces.",
	"To construct Beadeaux, the Quadav have stolen large quantities of the mythril from Bastok.",
	"The web-filled Crawlers' Nest is home to the crawlers that plague the Rolanberry Fields.",
	"In direct contrast to the highlands that surround it, the Pashhow Marshlands are a wet, swampy landscape.",
	"The countless bogs and floating islands of vegetation make the Pashhow Marshlands extremely difficult to traverse.",
	"For centuries, Rolanberry Fields has been used to cultivate fields of the sweet fruit known as the rolanberry.",
	"Rolanberries are considered a delicacy by Humes and the Elvaan.",
	"Farmers in Rolanberry Fields have perfected their methods of agriculture, now able to harvest the sweet berries year round.",
	"Three great bridges at the Rolanberry Fields' northeastern tip connect the region with its neighboring areas.",
	"The Lord Bolicevre Bridge connects the Rolanberry Fields to the Batallia Downs.",
	"The Market Bridge connects the Rolanberry Fields to the Grand Duchy of Jeuno.",
	"The Great Jeuno Bridge connects the Rolanberry Fields to the Sauromugue Champaign.",
	"Qulun Dome is a dark chamber beneath the Beastmen stronghold of Beadeaux and is the domain of the Quadav leader Za'Dha Adamantking.",
	"Belka, Pourette, and Taraihi-Perunhi will sell items from Derfland when their country is in control of the region.",
	"With the exception of the volcanoes in the north, Elshimo Island is characterized by its wide expanses of thick jungle.",
	"Elshimo Island is an island to the southeast of Mindartia, with labyrinthine jungles and caves.",
	"Kazham is a fishing village founded some four hundred years ago on the northern tip of Elshimo Island.",
	"Mithra form nearly half of Kazham's population and support the village by hunting and fishing.",
	"Kazham is self-governed, and all matters are judged by councils headed by Chieftainness Jakoh Wahcondalo.",
	"Flame Spouts in Ifrit's Cauldron require either waiting 3 Vana'diel hours or an Ice Cluster to pass.",
	"The tropical Yhoator Jungle covers most of the Elshimo Uplands and is teeming with the ruthless Tonberries.",
	"The Ranguemont Pass has long been considered the only road through the \"Northern Wall.\"",
	"Rodellieux, Vichuel, and Sheia Pohrichamaha will sell items from Fauregandi when their country is in control of the region.",
	"The Dangruf Wadi is a small gorge located near Mount Dangruf, an active volcano.",
	"The Korroloka Tunnel is located deep beneath the sea floor and was used by the Galka to flee to the Quon Continent.",
	"The interior of the Korroloka Tunnel is quite beautiful and is formed from a terrestrial coral.",
	"The Korroloka Tunnel is known as a place of tragedy and death to Galka, where the coral thrived on the blood of fallen comrades.",
	"Situated to the north of Bastok, North Gustaberg is a valley surrounded by steep mountains.",
	"North Gustaberg is separated into east and west areas by towering cliffs.",
	"The Gustaberg area remains desolate due to various mineral run-offs which contaminate the river water.",
	"The spectacular Drachenfall, located in North Gustaberg, is considered to be one of the wonders of Vana'diel.",
	"A tributary of the Dalha River, Obere Creek is located in North Gustaberg.",
	"The Palborough Mines were once a Quadav settlement until mythril, a rare ore, was discovered in its walls.",
	"Spreading out to the south of Bastok is the rocky terrain of South Gustaberg.",
	"Plentiful with ore, hundreds of tunnels and mine shafts have been dug beneath South Gustaberg by Humes and Quadav alike.",
	"The Morhen Lighthouse can be found on the cliffs lining the Bastore Sea, guiding the way for the ferries and airships.",
	"The Waughroon Shrine is sacred to the Quadav, located within their ancestral homelands that have become the Palborough Mines.",
	"The Zeruhn Mines were dug out of the Mines District of Bastok when a vein of Darksteel Ore was discovered within.",
	"Because of its location within the walls of Bastok, Zeruhn Mines is safer for miners than the nearby Palborough Mines.",
	"Evelyn, Apairemant, and Nya Labiccio will sell items from Gustaberg when their country is in control of the region.",
	"Bibiki Bay in the southeast of Mindartia looks out on the Gugru Blue.",
	"Bibiki Bay is sheltered by a multitude of tiny islands.",
	"The tranquil waters of Bibiki Bay were once used by Tarutaru fisherfolk to farm vast quantities of shellfish and seaweed.",
	"After the Crystal War, the cultivation of Bibiki Bay was abandoned as the Mithra brought their expertise in fishing to the mainland.",
	"The Fishermen's Guild, seeing Bibiki Bay's potential, recently paid for the right to begin fishing in the area.",
	"The Fishermen's guild has made its small fishing vessels in Bibiki Bay known as Manaclippers available for use by adventurers.",
	"The Buburimu Peninsula is located on the east side of the Pamtam Straits.",
	"On the eastern tip of Buburimu Peninsula, a strangely shaped rock formation can be found called the Kibubu Lighthouse.",
	"The dark, maze-like Labyrinth of Onzozo is littered with the bones of both fallen adventurers and prey alike.",
	"The Manaclipper is large fishing barge that takes a variety of routes through Bikibi Bay.",
	"The Maze of Shakhrami was formed long ago, when water from the rivers above seeped through and ate away at the rocks below.",
	"The twisting canyons of Tahrongi were carved thousands of years ago when powerful rivers ran through the region.",
	"Yafafa, Fiva, and Ahyeekih will sell items from Kolshushu when their country is in control of the region.",
	"Located just off the southwest coast of the continent of Quon, the Kuzotz region is made up of a number of tiny islands.",
	"The Eastern Altepa Desert, an arid desert wasteland, makes up the eastern half of Zepwell Island.",
	"Remnants of the ancient Galkan civilization that once thrived dot the Eastern Altepa Desert landscape.",
	"In the southwest corner of the Eastern Altepa Desert, the Oasis of Gatidav is a popular spot among fishers and adventures alike.",
	"Once a thriving metropolis for the proud Galka, the Quicksand Caves still house numerous monolithic pillars and statues.",
	"Rabao, supported by the Rabao Spring, lies towards the north end of Zepwell Island and is surrounded by the vast Altepa Desert.",
	"Enterprising merchants have erected tent-shops in Rabao in an effort to capitalize on stranded adventurers in need of aid.",
	"The Western Altepa Desert, an enormous expanse of desert, covers the entire western half of Zepwell Island.",
	"In the center of the Western Altepa Desert rises Revelation Rock, once used by the Galka as a location for spiritual training.",
	"The Oasis of Hubol is one of the few hospitable locations in Western Altepa Desert.",
	"Before Zepwell Island was overrun by Antica, Galka would climb to the top of Revelation Rock to await their Journey of Rebirth.",
	"Vattian, Patolle, and Nhobi Zalkia will sell items from Kuzotz when their country is in control of the region.",
	"The \"Boyahda Tree\", the largest tree of Zi'Tah, is said to have lasted tens of thousands of years.",
	"The Dragon's Aery, or nest, while home to some more common animals, is often guarded by one of two powerful Wyrms.",
	"The Hall of the Gods is the final safe resting place before entering the vast etheral expanses of Tu'Lia.",
	"The Hall of the Gods contains a grand statue of the Dawn Goddess Altana, as well as a large statue of Promathia.",
	"The amphitheater-like Ro'Maeve is comprised of a series of levels leading up to the top, where one can enter the Hall of the Gods.",
	"The moongates in Ro'Maeve open on full moon nights between 18:00-6:00. They can also be opened with a Moongate Pass.",
	"The Sanctuary of Zi'Tah is the coniferous forest that lies at the entrance to the Li'Telor region.",
	"Very little light reaches the forest floor of the Sanctuary of Zi'Tah, blocked by trees that are thousands of years old.",
	"Throughout the Sanctuary of Zi'Tah are illuminated crystals that shine eerily even during the day.",
	"The Sanctuary of Zi'Tah was believed to be the region of gods, and was rare for people to visit unless on pilgrimage to Ro'Maeve.",
	"Galdeo, Attarena, and Otete will sell items from Li'Telor when their country is in control of the region.",
	"The Aydeewa Subterrane, covered in subterranean plants, is an extensive network of tunnels lying beneath the Wajaom Woodlands.",
	"The Aydeewa Subterrane was once a site of the ancient Olduum civilization until sinking almost completely into the ocean.",
	"Traces of the Olduum civilization's past can still be seen in the stone pillars and altars scattered about the Aydeewa Subterrane.",
	"The Empire of Aht Urhgan maintained the Aydeewa Subterrane until recently, when increasing beastman threats forced them to withdraw.",
	"The Aydeewa Subterrane is plagued with Qiqirn and Mamool Ja thieves looking for treasure among the ruins.",
	"The capital of the Mamool Ja, Mamook was built deep in a forest on a peninsula west of the Aht Urhgan Empire.",
	"To control parasite infestations, the wooden structures that cover Mamook are burned down and rebuilt every few years.",
	"Like their equipment, the few intricate decorative metals in Mammok were created by prisoners taken by Mamool Ja.",
	"Sacred stones in each area of Mamook are believed to harbor the spirits of fallen Mamool Ja heroes and protect from evil.",
	"The Wajaom woodlands cover a vast stretch of land to the west of the Aht Urhgan capital.",
	"Wajaom means \"abundance\" in the language of Aht Urhgan.",
	"The Wajaom woodlands are home to a rich variety of fauna, from birds that hover in the air to bees that build enormous hives.",
	"Situated deep within Movalpolos, Mine Shaft #2716 is the deepest shaft dug by the moblins and appears to go on forever.",
	"The blue and red gates in Newton Movalpolos can be moved by trading a jar of Firesand to the nearby Furnace Hatch.",
	"As the Moblins drill through Vana'diel's crust, they are constantly moving their homes, water tanks, and scaffolding.",
	"The continuous advancement of Movalpolos makes it difficult to locate the city at any one time.",
	"While there are some Moblins who emerge to sell ores, most of the tribe's members have cut themselves off from the outside world.",
	"The subterranean city of Movalpolos was dug and built by a tribe of Goblins referred to as the Moblins.",
	"The Moblins are known for their exceptional smithing and alchemy skills.",
	"Moblin achievements include complex drilling apparatuses, floodlights, and several advancements in exotic fields such as bionics.",
	"Bagnobrok, Vendavoq, and Prestapiq will sell items from Movalpolos when their country is in control of the region.",
	"During the Crystal War, the Batallia Downs was the location of the infamous Battle of Jeuno.",
	"The scars left from the infamous Battle of Jeuno still litter the Batallia Downs.",
	"The Achaque Mountains in the north of the Batallia Downs prevent possible intruders while hampering the travel of adventurers.",
	"The Artisan Bridge on the Batallia Downs' far eastern shore connects the Norvallen Region and the Grand Duchy of Jeuno.",
	"Carpenters' Landing is comprised of unconnected docks providing access to the barge that travels down the Phanauet Channel.",
	"While Carpenters' Landing is small in area, getting around on the barge is best left for those who prefer a scenic route.",
	"During the Crystal War, the Eldieme Necropolis was the site of fierce battles whose spirits still roam the tombs below.",
	"Deep within the recesses of the Orcish stronghold of Davoi is the Monastic Cavern, home to the leaders of the Orcs.",
	"Once a welcoming, peaceful Elvaan monastery, the Monastic Cavern is now dangerous for any to step foot in.",
	"Mille, Machielle, and Posso Ruhbini will sell items from Norvallen when their country is in control of the region.",
	"Behemoth's Dominion is a cavernous subterranean dwelling buried deep inside Qufim Island.",
	"In addition to the Behemoths, scores of undead also roam Behemoth's Dominion seeking to surprise unsuspecting adventurers.",
	"Delkfutt's Tower in the North of Qufim Island is overrun by Gigas who were trapped there at the end of the Crystal War.",
	"Isolated in the gloomy Delkfutt's Tower, the Gigas are constantly searching for a way to get back to their homeland.",
	"Towering over the surroundings in the center of Qufim Island is an enormous spirelike structure: Delkfutt's Tower.",
	"An island to the north of Jeuno, Qufim Island is home to Gigas unable to survive the depths of Delkfutt's Tower.",
	"A long tunnel under the Sea of Shu'Meyo connects Port Jeuno to Qufim Island's rocky cliffs.",
	"Takiyah, Eugballion, and Millerovieunet will sell items from Qufim when their country is in control of the region.",
	"The Bostaunieux Oubliette prison is not currently in use by the Kingdom of San d'Oria.",
	"The deeper recesses of the Bostaunieux Oubliette are accessible only through a guarded trap door.",
	"Blessed by the abundant waters of the Cheval River, the wildlife in East Ronfaure has flourished for centuries.",
	"The massive Fort Ghelsba, reinforced with towering logs, is home to the frontline troops of the Orcish Empire.",
	"The Orcs prepare for battle with San d'Oria by constructing various siege weapons inside Fort Ghelsba.",
	"Ghelsba Outpost is home to the Vilebloods, who are led by the merciless Warchief Vatgit.",
	"Only the most fearless, vicious, bloodthirsty Orcs are selected to be a part of Orc Warchief Vatgit's ranks.",
	"Horlais Peak is the highest mountaintop above Fort Ghelsba, containing the famous Horlais hot springs.",
	"The Orcs used Elvaan slaves to dig the Yughott Grotto, intended to lead under the walls of the San d'Orian citadel.",
	"Faustin, Corua, and Jourille will sell items from Ronfaure when their country is in control of the region.",
	"East Sarutabaruta is known for its two rivers the Zanbibi River and the Nompipi River.",
	"Lake Tepokalipuka and several Horutoto Ruins are famous sights located in the tropical East Sarutabaruta.",
	"To the south of East Sarutabaruta lies the coast of the Pamtam Straits.",
	"The Pamtam Straits is the body of water between the Mindartia Continent and Elshimo Island.",
	"Full Moon Fountain is an ancient fountain discovered by the first Star Sibyl.",
	"Legend has it, the Full Moon Fountain is where the first Star Sibyl was bestowed the gift of magic.",
	"Full Moon Fountain is said to contain the vast power of the stars and moon and is home to the legendary guardian beast Fenrir.",
	"A peace treaty between the Yagudo and Windurst prevents the incursion of Federation forces into their stolen territory, Giddeus.",
	"Using their claws and sharp beaks, the Yagudo carved caves out of the surrounding cliffs to serve as their homes inside Giddeus.",
	"On a daily basis, the Yagudo of Giddeus perform short pilgrimages around the area, stopping at each of the numerous altars.",
	"The Horutoto Ruins are ancient towers spread across the plains of Sarutabaruta.",
	"No one is certain why the massive structures known as the Horutoto Ruins were built.",
	"The powerful magical energy emanating from the Horutoto Ruins has been the center of Tarutaru scientific investigation for decades.",
	"The Toraimarai Canal was named after the famed explorer and mage Torai-Marai.",
	"The Toraimarai Canal underneath Windurst provides water to the Great Star Tree and is home to a wide variety of creatures.",
	"With multiple levels and a number of dead-ends, venturing into the Toraimarai Canal often leads to certain death.",
	"Ruins of an ancient civilization dot the Sarutabaruta area around Windurst.",
	"In the mystical place known as Starfall Hillock in West Sarutabaruta, stars are said to fall from the heavens on cold nights.",
	"Somn-Paemn, Milva, and Baehu-Faehu will sell items from Sarutabaruta when their country is in control of the region.",
	"The Tavnazian Archipelago is a tiny island off the west coast of Quon which was once home to the proud nation of Tavnazia.",
	"Before a devastating explosion during the Crystal War, the Tavnazian Archipelago was a peninsula connected with the mainland.",
	"A small dragon can occasionally be seen swooping down and skimming across the Leremieu Lagoon in Lufaise Meadows.",
	"Emaliveulaux, Deguerendars, and Alizabe will sell items from the Tavnazian Archipelago when their country is in control of the region.",
	"Western Adoulin is the hub for adventurers who were afforded safe passage to assist in the city's long-term settlement project.",
	"Western Adoulin serves as the home base for the Sacred City of Adoulin's pioneering plans and is the entranceway to the city.",
	"Eastern Adoulin fans out from Castle Adoulin, as both the administrative center of the city and a residential haven for the nobility.",
	"Spacious manses line the streets of Eastern Adoulin, and the aristocrats of Adoulin can be seen taking in the sights and sounds.",
	"The Rala Waterways have various Sluice Gates that are accessible or locked depending upon the day and time.",
	"The Rala Waterways are a gigantic expanse of interconnected underground straits spanning from east to west by means of the Big Bridge.",
	"The two hundred year old Rala Waterways are a source of water for Adoulin, and home to all manner of unfriendly creatures.",
	"Tibelda, Palguevion, and Alizabe will sell items from Valdeaunia when their country is in control of the region.",
	"A boulder blocks occasionally passage inside Kuftal Tunnel, but opens at specific times based on moon phase.",
	"Aulavia, Millechuca, and Lebondur will sell items from Vollbow when their country is in control of the region.",
	"Aht Urhgan Whitegate features two ports, one facing the inland sea to the north and another facing the open sea to the south.",
	"The Imperial Ward lies behind a colossal white wall that separates the district from Aht Urhgan Whitegate.",
	"Records tell of six unfortunate fellows dying under very suspious circumstances in the Gusgen Mines.",
	"Complete with a railway system for mine carts, the Gusgen Mines were heavily mined for many years but now remain abandoned.",
	"The vast grasslands of Konschtat Highlands are situated just north of the Republic of Bastok.",
	"In contrast to the surrounding Bastok Mountains, the Konschtat Highlands are abundant with an array of alpine wildlife.",
	"Bastok constructed numerous windmills throughout the Konschtat Highlands to harness the powerful winds called \"Odin's Wrath\".",
	"According to a treaty, San d'Oria provides a portion of their grain crops in exchange for the use of Bastok's windmills.",
	"The grasslands that make up the La Theine Plateau are located high above the surrounding areas.",
	"The La Theine Plateau was once known for the flocks of wild chocobos that dotted the meadows.",
	"The La Theine Plateau is now overrun with giant sheep that are herded by the local Elvaan.",
	"The La Theine Plateau is characterized by deep crevices that seem to tear apart the land; torrential rainfall is also common.",
	"As a result of the heavy precipitation, rainbows can frequently be spotted while traveling through the La Theine Plateau.",
	"The enormous expanse of the Valkurm Dunes can be found along the Bhefhel Gulf.",
	"Rosswald, Phamelise, and Bin Stejihna will sell items from Zulkheim when their country is in control of the region.",
	"Reisenjima is a remote and sacred island. It is the land of the gods in the Far East.",
	"The Pioneers' Coalition is led by maester Lhe Lhangavo of the Order of Kareiyh.",
	"The Pioneers' Coalition is tasked with cultivating the local territories of Ulbuka and gathering local resources.",
	"The Pioneers' Coalition offers items that help Pioneers gather through harvesting, excavation, logging, and mining.",
	"The Peacekeepers' Coalition is led by maester Gratzigg of the Order of Vocane.",
	"The Peacekeepers' Coalition is tasked with the security and defense of the city of Adoulin.",
	"The Peacekeepers' Coalition offers unique provisions, armor, and weapons that adventurers can purchase with Bayld.",
	"The Couriers' Coalition is led by maester Reginald of the Order of Shneddick.",
	"The Couriers' Coalition transports supplies to the front lines of the Ulbukan colonization effort.",
	"The Scouts' Coalition is led by maester Margret of the Order of Haverton.",
	"The Scouts' Coalitions' primary task is gathering intelligence about the local terrain of Ulbuka.",
	"The Scouts' Coalitions' secondary task is analyzing unknown materials to assist the colonization movement.",
	"The Scouts' Coalition offers area maps and various information that will assist pioneers in exploring the continent.",
	"The Mummers' Coalition is led by maester Flaviria of the Order of Thurandaut.",
	"The Mummers' Coalitions' primary task is keeping spirits up through fun and entertainment.",
	"The Mummers' Coalition ensures adventurers' morale remains high as they brave the harsh wilderness of Ulbuka.",
	"The Mummers' Coalition offers carnival-style games which allow players to accumulate Mummers' Medals.",
	"The Inventors' Coalition is led by maester Amchuchu of the Order of Orvail.",
	"The Inventors' Coalition develops new tools and equipment to support pioneers and Ulbukan colonization.",
	"The Inventors' Coalition offers equipment and weapon augmentation, as well as tinctures to provide temporary bonuses.",
	"Balasiel, in Southern San d'Oria, will start the quest \"A Knight's Test\", allowing you to become a Paladin.",
	"Gumbah, in Bastok Mines, will start the quest \"Blade of Darkness\", allowing you to become a Dark Knight.",
	"Brutus, in Upper Jeuno, will start the quest \"Path of the Beastmaster\", allowing you to become a Beastmaster.",
	"Bki Tbujhja, in Lower Jeuno, will start the quest \"Path of the Bard\", allowing you to become a Bard.",
	"Perih Vashai, in Windurst Woods, will start the quest \"The Fanged One\", allowing you to become a Ranger.",
	"Jaucribaix, in Norg, will start the quest \"Forge Your Destiny\", allowing you to become a Samurai.",
	"Kaede, in Port Bastok, will start the quest \"Ayame and Kaede\", allowing you to become a Ninja.",
	"Ceraulian, in Port San d'Oria, will start the quest \"The Holy Crest\", allowing you to become a Dragoon.",
	"The House of the Hero, in Windurst Walls, will start the quest \"I Can Hear a Rainbow\", allowing you to become a Summoner.",
	"Waoud, in Aht Urhgan Whitegate, will start the quest \"An Empty Vessel\", allowing you to become a Blue Mage.",
	"Ratihb, in Aht Urhgan Whitegate, will start the quest \"Luck of the Draw\", allowing you to become a Corsair.",
	"Shamarhaan, in Bastok Markets, will start the quest \"No Strings Attached\", allowing you to become a Puppetmaster.",
	"Laila, in Upper Jeuno, will start the quest \"Lakeside Minuet\", allowing you to become a Dancer.",
	"Erlene, in The Eldieme Necropolis [S], will start the quest \"A Little Knowledge\", allowing you to become a Scholar.",
	"Sylvie, in Western Adoulin, will start the quest \"Dances with Luopans\", allowing you to become a Geomancer.",
	"Octavien, in Eastern Adoulin, will start the quest \"Children of the Rune\", allowing you to become a Rune Fencer.",
	"The website bg-wiki.com is a Final Fantasy resource created and maintained by the player community.",
	"The website ffxiah.com allows players to view in-game auction house information for all worlds.",
	"The website ffxiclopedia.com is a wiki dedicated to collecting all information related to the game.",
	"The tranquil waters of Purgonorgo Isle were once used by Tarutaru fisherfolk to farm vast quantities of shellfish and seaweed.",
	"With the exception of Sarutabaruta in the south, the continent of Mindartia is mainly comprised of dry, rocky badlands.",
	"Corn and popotoes are the staple food source of Windurst, with Dhalmel and Rarab kept as livestock.",
	"The Federation of Windurst is the homeland of the Tarutaru, with the magical city of Windurst as its center of civilization.",
	"The Windurstian government consists of a Parliament of Patriarchs, high-ranking members of the magic ministries, and the Star Sybil.",
	"Windurst's Star Sybil performs \"Moon Readings\" annually in the Full Moon Fountain to predict the course of the next year.",
	"Aubades are songs that enhance Sleep Resistance.",
	"Ballads are songs that restore MP.",
	"Carols are songs that increase Magic Evasion against specific elements.",
	"Capriccios are songs that enhance Petrification Resistance.",
	"Dirges are songs that give a flat reduction in Enmity.",
	"Elegies are songs that reduce an enemies Attack Speed.",
	"Etudes are songs that enhance base Stats.",
	"Fantasias are songs that enhance Blind Resistance.",
	"Finales are songs that remove beneficial buff effects from enemies, similar to Dispel.",
	"Gavottes are songs that enhance Bind Resistance.",
	"Hymnuses are songs that grant a Reraise effect.",
	"Lullabies are songs that are a form of light-based sleep.",
	"Madrigals are songs that enhance melee Accuracy.",
	"Mambos are songs that enhance Evasion.",
	"Marches are songs that increase melee Attack Speed and decrease Spell Recast Time.",
	"Mazurkas are songs that enhance Movement Speed.",
	"Minnes are songs that enhance Defense.",
	"Minuets are songs that enhance Attack and Ranged Attack.",
	"Nocturnes are songs that decrease an enemy's magic accuracy and increases its spellcasting time, similar to Addle.",
	"Operettas are songs that enhance Silence Resistance.",
	"Paeons are songs that restore HP, similar to Regen spells.",
	"Pastorals are songs that enhance Poison Resistance.",
	"Preludes are songs that enhance Ranged Accuracy.",
	"Requiems are songs that bestow a light-based Damage Over Time effect upon an enemy.",
	"Rounds are songs that enhance Curse Resistance.",
	"Scherzos are songs that give a specific type of damage reduction.",
	"Sirventes are songs which reduce Cumulative Enmity lost over time.",
	"Threnodies are songs that reduce the resistance of enemies to particular elements.",
	"Virelais are songs that Charm an enemy.",
	"Divine Magic focuses on damaging and debilitating enemies with light elemental white magic spells.",
	"Enfeebling Magic applies negative status effects to one or more enemy targets.",
	"Enhancing Magic includes spells that enhance various attributes of the target.",
	"Healing Magic includes restorative spells to heal and remove negative status effects from allies.",
	"Dark Magic focuses on damaging or absorbing from an enemy to enhance the caster.",
	"Elemental Magic focuses on causing magical damage to enemies.",
	"Specializing in the arts of battle, Warriors can equip almost all of the types of weapons.",
	"With bodies that double as deadly weapons, Monks attack enemies with explosive punches and kicks.",
	"By using recovery spells and healing magic, White Mages ensure a party's survival.",
	"Through devastating magic spells, Black Mages bring tremendous firepower to the battlefield.",
	"As fighter-mages, Red Mages can can utilize both black and white magic, as well as the arts of the sword.",
	"Specializing in covert actions, Thieves are masters in the art of controlling the flow of battle.",
	"Through long hours of spiritual training, Paladins use white magic spells to protect their allies.",
	"To strengthen themselves in battle, Dark Knights use black magic spells that torment their enemies.",
	"Experts in monster research, Beastmasters are able to communicate with and control the animals of Vana'diel.",
	"With music as their weapons, Bards use songs to boost their allies and weaken their enemies.",
	"Skilled with the bow and arrow, Rangers are experts in the field of hunting and tracking.",
	"Through the study of Far Eastern martial arts techniques, Samurais have devoted their lives to the great katana.",
	"Training in the forbidden arts of the Far East, Ninjas deal large amounts of damage with shurikens and spells.",
	"With faithful wyverns by their sides, Dragoons surprise their enemies with their extraordinary jumping abilities.",
	"By making pacts with the legendary Avatars, Summoners unleash devastating forbidden magic.",
	"Using fell magic mastered from their opponents, Blue Mages decimate their enemies with elegantly curved blades.",
	"Descendants of dauntless pirates, Corsairs rely on luck and a Hexagun to alter the stakes of battle.",
	"Utilizing a customizable puppet \"automaton\", Puppetmasters entertain crowds and confound their enemies.",
	"With their aggressive steps, Dancers weave forbidden magic upon themselves and their enemies.",
	"With extensive knowledge of ancient martial theory, Scholars wield dual schools of magic.",
	"Harnessing the elemental powers of nature, Geomancers strengthen their allies and enervate their enemies.",
	"Quick with a blade as well as an incantation, Rune Fencers employ arcane runes to sway the tide of battle.",
	"Communication is good for doing events smoothly.",
	"The Hall of the Gods houses one of the few monuments to the Twilight God Promathia that still stands today.",
	"Valaineral R Davilles, the Grassblade Noble, is the first cousin to the current San d'Orian king, Destin R D'Oraguille.",
	"Elivira Gogol, the Divine Markswoman, is an accomplished tactician and captain of the Gold Musketeers.",
	"Haja Zhwan, the Roving Wildsword, is a descendant of the legendary High Matriarch Vhizeyah from Mithran folklore.",
	"The Empire of Aht Urhgan officially adopted a neutral stance towards the Crystal War.",
	"Azima, the Alchemical Arcanist, is the Bastokan area's most accomplished and dangerous bounty hunter.",
	"Dalzakk, the Affable Wayfarer, is one of Bastok's greatest martial artists.",
	"Choh Moui, the Venomous Verminess, is the inventor of multifarious foods designed to coax optimal performance out of pets.",
	"The Three-dawn Scourge was a lethal sickness causing chain-link bruises and high-pitched fever in the victim.",
	"In Rise of the Zilart, stop the Zilart from opening the Gate of the Gods, a portal that could destroy Vana'diel.",
	"In Chains of Promathia, confront \"The Emptiness\" and a prophecy tied to the god Promathia and a mysterious pale child.",
	"In Treasures of Aht Urhgan, investigate the Empire's secrets, including the Astral Candescence and the Dark Rider.",
	"In Wings of the Goddess, time-travel to the Crystal War and help ease suffering while others seek to alter history.",
	"In Seekers of Adoulin, join the colonization of Ulbuka, facing fierce Naakuals and discovering the land's dark mysteries.",
	"In A Crystalline Prophecy, a giant crystal appears, prompting a quest to uncover its secrets and a boy resembling Aldo.",
	"In A Moogle Kupo d'Etat, a rundown Mog House sparks a bizarre, nightmarish chain of events across mooglekind.",
	"In A Shantotto Ascension, Shantotto's strange behavior and claim to rule prompt a quest to uncover the cause.",
	"In Vision of Abyssea, new maws lead to Abyssea, a crumbling world with blood-red skies, hope, and looming destruction.",
	"In Scars of Abyssea, adventurers explore deeper, finding riches and survivors defending Pulse Martellos from fell hordes.",
	"In Heroes of Abyssea, adventurers join the Resistance, face savage hordes, and uncover Abyssea's darkest secrets.",
	"In Rhapsodies of Vana'diel, a vision of darkness and a mysterious \"student\" lead to a quest to prevent an impending apocalypse.",
	"In The Voracious Resurgence, robed figures and legendary eggs reveal a dark conspiracy that threatens Vana'diel's fabric.",
	"FFXI has the series' largest soundtrack, with nearly 200 tracks and over 11 hours of music across album releases.",
	"FFXI was announced at the Japanese Square Millennium Event in 2000, along with the announcement for Final Fantasy X.",
	"The idea for an MMO Final Fantasy came to Hironobu Sakaguchi after being impressed by the western MMORPG EverQuest.",
	"FFXI initially released in Japan on May 16th, 2002 for the PS2.",
	"FFXI released for PC in Japan on November 7th, 2002.",
	"FFXI released for PC in the US and Canada on October 28th, 2003, and included Rise of the Zilart.",
	"FFXI released for PS2 in the US and Canada on March 23rd, 2004, and included Rise of the Zilart.",
	"FFXI released for PC in Europe and Australia on September 17th, 2004, and included Rise of the Zilart.",
	"FFXI released for Xbox 360 in the US and Canada on April 18th, 2006, and included RotZ, CoP, and ToAU.",
	"FFXI released for Xbox 360 in Japan on April 20th, 2006, and included RotZ, CoP, and ToAU.",
	"FFXI released for Xbox 360 in Europe and Australia on April 21st, 2006, and included RotZ, CoP, and ToAU.",
	"Rise of the Zilart release in Japan for PC and PS2 on April 17th, 2003.",
	"Chains of Promathia released for PC and PS2 in Japan on September 16th, 2004.",
	"Chains of Promathia released for PS2 in the US and Canada on September 21st, 2004.",
	"Chains of Promathia released for PC in the US, Canada, Europe, and Australia on September 21st, 2004.",
	"Treasure of Aht Urhgan released for PS2 and PC in the US and Canada on April 18th, 2006.",
	"Treasure of Aht Urhgan released for PS2 and Xbox 360 in Japan on April 20th, 2006.",
	"Wings of the Goddess released for PS2 and Xbox 360 in the US and Canada on November 20th, 2007.",
	"Wings of the Goddess released for PC in the US and Canada on November 21st, 2007.",
	"Wings of the Goddess released for PS2 and Xbox 360 in Japan on November 22nd, 2007.",
	"Wings of the Goddess released for PC in Japan and Europe on November 22nd, 2007.",
	"Wings of the Goddess released for PC and Xbox 360 in Australia on December 6th, 2007.",
	"A Crystaline Prophecy released for PS2, PC, and Xbox 360 in the US and Canada on March 22nd, 2009.",
	"A Crystaline Prophecy released for PS2 in Japan on March 23rd, 2009.",
	"A Crystaline Prophecy released for PC and Xbox 360 in Japan, Europe, and Australia on March 23rd, 2009.",
	"A Moogle Kupo d'Etat released for PS2, PC, and Xb360 in the US and Canada on July 5th, 2009.",
	"A Moogle Kupo d'Etat released for PS2 in Japan on July 6th, 2009.",
	"A Moogle Kupo d'Etat released for PC and Xbox 360 in Japan, Europe, and Australia on July 6th, 2009.",
	"A Shantotto Ascension released for PC and Xbox 360 in Europe and Australia on October 25th, 2009.",
	"A Shantotto Ascension released for PS2, PC, and Xbox 360 in Japan, the US, and Canada on October 26th, 2009.",
	"Vision of Abyssea released for PS2, PC, and Xbox 360 in Japan on June 6th, 2010.",
	"Vision of Abyssea released for PS2, PC, and Xbox 360 in the US and Canada on June 7th, 2010.",
	"Vision of Abyssea released for PC and Xbox 360 in Europe and Australia on June 8th, 2010.",
	"Scars of Abyssea released for PS2 in the US and Canada on August 23rd, 2010.",
	"Scars of Abyssea released for PC and Xbox 360 in the US, Canada, Europe, and Australia on August 23rd, 2010.",
	"Scars of Abyssea released for PS2, PC, and Xbox 360 in Japan on August 24th, 2010.",
	"Heroes of Abyssea released for PS2 in the US and Canada on November 23rd, 2010.",
	"Heroes of Abyssea released for PC and Xbox 360 in the US, Canada, Europe, and Australia on November 23rd, 2010.",
	"Heroes of Abyssea released for PS2, PC, and Xbox 360 in Japan on November 24th, 2010.",
	"Seekers of Adoulin released for PC and Xbox 360 in the US and Canada on March 26th, 2013.",
	"Seekers of Adoulin released for PS2 in Japan on March 27th, 2013.",
	"Seekers of Adoulin released for PC and Xbox 360 in Japan, Europe, and Australia on March 27th, 2013.",
	"FFXI released for Steam in the Europe, the US, Canada, and Japan on April 19th, 2013.",
	"Rhapsodies of Vana'diel was released in 3 parts, starting on May 14th, 2015, and finishing on November 10th, 2015.",
	"Support for the PS2 and Xbox 360 version of FFXI ended on March 31st, 2016.",
	"The Voracious Resurgence was released in 11 parts, starting on August 6th, 2020, and finishing on March 10th, 2023.",
	"Rhapsodies of Vana'diel was initially announced as the final main scenario, until The Voracious Resurgence in 2020.",
	"Rhapsodies of Vana'diel was the last content released prior the end of service for Xbox 360 and PS2 versions in March 2016.",
	"The PS2 version of FFXI wasn't released in Europe, as the console's hard drive wasn't available in the region.",
	"Chains of Promathia is the only expansion with no new jobs accompanying it's release.",
	"Japan was the only region that received the Seekers of Adoulin expansion on PS2.",
	"Avatars are the powerful beings and lesser deities in Vana'diel, and can be encountered as both allies and enemies.",
	"Avatars are heavily involved in shaping Vana'diel, and often play an important role in the storylines of FFXI.",
	"Celestial Avatars were once mortal creatures whose great acts of virtue moved Altana, elevating them to becoming an Avatar.",
	"The Sleeping Gods, aka Celestial Avatars, reside within protocrystals hidden inside Elemental Cloisters across the world.",
	"The Terrestrial Avatars are mighty beasts tasked with protecting the Mothercrystals.",
	"The Sleeping God Ifrit is known as \"Avatar of Fire\".",
	"Ifrit was a fearsome general named Frit, who selflessly prayed to Altana for those he cared about.",
	"The Sleeping God Shiva is known as \"Avatar of Ice\".",
	"Shiva was a young, wise, and competent ruler of a small kingdom situated in the south of Vana'diel, loved by her people.",
	"The Sleeping God Garuda is known as \"Avatar of Wind\".",
	"Garuda was a small bird raised by a young prince who sought out the aid of the King of Birds.",
	"The Sleeping God Titan is known as \"Avatar of Earth\".",
	"Titan was a wrongly condemned member of a tribe of giants (the Titans) in conflict with a neighboring city.",
	"The Sleeping God Ramuh is known as \"Avatar of Lightning\".",
	"Ramuh was a sage from a nation on the Buburimu Peninsula who helped his country to prosper and develop advanced technology.",
	"The Sleeping God Leviathan is known as \"Avatar of Water\".",
	"Leviathan was a great sea serpent who used to terrorize the Gugru Sea in protest of the development of sea commerce.",
	"The Sleeping God Alexander is known as \"The Colossus\".",
	"Alexander was defeated 900 years ago in Ragnarok, a battle between him and Odin.",
	"The Sleeping God Odin is known as \"The Harbinger\".",
	"Odin was once a Sleeping God, but now roams free across Vana'diel after the beastmen's attempts to harness his power.",
	"The Terrestrial Avatar Bahamu is known as \"Conqueror of the Skies\".",
	"Bahamut made an ancient pact to protect the Mothercrystals and defeat the Keeper of the Apocalypse when the time came.",
	"Bahamut is also known as the \"Wyrm King\" due to his control of the wyrms of Vana'diel.",
	"The Terrestrial Avatar Carbuncle is known as \"Bringer of Rainbows\".",
	"Carbuncle is the first Avatar that summoners form a pact with.",
	"Carbuncle guides summoners through their mastery of summoning magic.",
	"The Terrestrial Avatar Chaos is known as \"The Voracious Beast\".",
	"Rather than being associated with a standard constellation, Chaos has a hidden constellation of black stars.",
	"The Terrestrial Avatar Diabolos is known as \"Ruler of Dreams\".",
	"Diabolos created the world of Dreamworld Dynamis to protect the enlightened races in the event of the apocalypse.",
	"The Terrestrial Avatar Fenrir is known as \"Guardian of the Moon\".",
	"Fenrir brought growth and flourishing to the continent of Mindartia and the Federation of Windurst until the Crystal War.",
	"The Terrestrial Avatar Phoenix is known as \"Fiery Bird of Resurrection\".",
	"While the body of Phoenix was destroyed many years ago, her flame burns strong in the Far East.",
	"The remnants of the Phoenix's power were forged into a blade that guides the warriors of the Far East.",
	"Phoenix can be resurrected once more should Altana ever demand contributions of the energies of all the other Avatars.",
	"Atomos is the devourer of time and serves to indiscriminately return dispensable time to the void.",
	"Altana created many Cait Siths to negate the timeline where the enlightened races are extinct after losing the Crystal War.",
	"There were initially ten black Cait Siths and ten white Cait Siths.",
	"The black Cait Siths eventually merge into a single entity, which is the one players can summon.",
	"Siren is a mysterious Avatar with a strong connection to the Lifestream of Vana'diel and the World Trees that mediate it.",
	"Many eons ago, five Terrestrial Avatars fought an evil presence that attempted to envelop and suffocate our world.",
	"At the dawn of time, the great crystal created two Supreme Beings: Promathia, god of darkness, and Altana, goddess of light.",
	"Altana, the Dawn Goddess and creator of Vana'diel, wept five tears down on the world and created of the five races.",
	"Promathia, the Twilight God and Altana's dark counterpart, is faceless and bound by chains he reportedly forged himself.",
	"Atomos consumes realities deemed unfit, depositing them in the \"Walk of Echoes.\"",
	"Atomos holds characteristics similar to the Supreme Beings, Altana and Promathia.",
	"Final Fantasy XI features music scored by Nobuo Uematsu, Kumi Tanioka, and Naoshi Mizuta.",
	"The Star Onions have released two albums of arranged Final Fantasy XI tracks.",
	"FFXI was almost titled simply \"Final Fantasy Online\" before being deemed worthy of being a numbered entry in the main series.",
	"A closed FFXI beta test took place in Japan in August of 2001, with a public version following in December.",
	"FFXI holds the most extensive soundtrack out of the series, with nearly 200 tracks totaling over 11 hours in listening time.",
	"Defeating Pixies will slowly cause them to not help you at all, and eventually become aggressive.",
	"The Humes built their city, the Republic of Bastok, in the wastes of Gustaberg.",
	"Humes possess near-equal abilities in all fields, and are physically-basic compared to other races.",
	"It is the Humes' adaptability that has spread them throughout the lands, making them the most numerous of the five races.",
	"Humes are said to suffer from the sin of Apathy.",
	"The most imposing of all the races, the Galka possess towering, bulky physiques.",
	"The Galkas' home city was destroyed hundreds of years ago by the Anticans, making the Galkan people refugees.",
	"Many Galka have settled in Bastok with the Humes; however, they are regarded as an underclass.",
	"Galkas are unique from other races in that they are all male and reproduce through reincarnation.",
	"Galka possess high Vitality and HP, but have the lowest MP of the five races.",
	"Galka are said to suffer from the sin of Rage.",
	"Native to the Kingdom of San d'Oria, the Elvaan are characterized by their tall, slender figures and large, pointed ears.",
	"Many Elvaan are deeply religious, possessing an unbreakable faith that is reflected in their everyday life.",
	"Elvaan are blessed with high Strength and Mind; however, also possessing low Intelligence.",
	"Elvaan are said to suffer from the sin of Arrogance.",
	"The cat-like race of Mithras possess a gender imbalance, with a high ratio of females to males.",
	"Only female Mithra are allowed away from the safety of their homeland to adventure around Vana'diel.",
	"Mithra possess excellent Agility and Dexterity, but lack Vitality and Charisma.",
	"Mithras are said to suffer from the sin of Envy.",
	"Residing in the Federation of Windurst, Tarutaru are famed for their discovery and development of magic.",
	"Tarutaru excel at magic, thanks to their high Intelligence; however, they have the lowest Strength with their small physique.",
	"Tarutaru are said to suffer from the sin of Cowardice.",
	"FFXI takes place in the world of Vana'diel, a diverse planet with regions ranging from blinding-hot deserts to ice-cold glaciers.",
	"Ancient lore states that Vana'diel was created as a playground for the Gods, who were spawned from an enormous, sentient Crystal.",
	"Chemist, Necromancer, Songstress/Super Idol, and Hell Magician are jobs that exist in FFXI but are unavailable to the player.",
	"Monberaux and Oshasha are the only klnown NPCs who are Chemists.",
	"Ancolain, Fardimant, and Louartain are the only known NPCs who are Necromancers.",
	"Mumor is the only known NPC who is a Songstress (aka Super Idol).",
	"Gariri, Kayeel-Payeel, and Lutete are the only known NPCs who are Hell Magicians.",
	"The name \'Schultz\" may refer to Gunther Schultz or Gunther Schultz II, both were famous tacticians.",
	"Gunther Schultz was a military strategist who led Bastok to victory and co-authored the original school of martial theory.",
	"Gunther Schultz II converted his father's work into a magical tome upon which the Scholar job is founded.",
	"Humanoid Killer is a term for a Killer Effect that intimidates only Player Characters.",
	"Killer Effects are a range of statuses, Job Traits, and circle abilities which convey an edge while fighting a specific Ecosystem.",
	"Beasts prey on Lizards.",
	"Lizards prey on Vermin.",
	"Vermin prey on Plantoids.",
	"Plantoids prey on Beasts.",
	"Aquans prey on Amorphs.",
	"Amorphs prey on Birds.",
	"Birds prey on Aquans.",
	"The Amorph Killer Job Trait will gain you a small amount of intimidation, damage taken and damage dealt bonus against Amorphs.",
	"The Aquan Killer Job Trait will gain you a small amount of intimidation, damage taken and damage dealt bonus against Aquans.",
	"The Arcana Killer Job Trait will gain you a small amount of intimidation, damage taken and damage dealt bonus against Arcana.",
	"The Beast Killer Job Trait will gain you a small amount of intimidation, damage taken and damage dealt bonus against Beasts.",
	"The Bird Killer Job Trait will gain you a small amount of intimidation, damage taken and damage dealt bonus against Birds.",
	"The Demon Killer Job Trait will gain you a small amount of intimidation, damage taken and damage dealt bonus against Demons.",
	"The Dragon Killer Job Trait will gain you a small amount of intimidation, damage taken and damage dealt bonus against Dragons.",
	"The Lizard Killer Job Trait will gain you a small amount of intimidation, damage taken and damage dealt bonus against Lizards.",
	"The Plantoid Killer Job Trait will gain you a small amount of intimidation, damage taken and damage dealt bonus against Plantoids.",
	"The Undead Killer Job Trait will gain you a small amount of intimidation, damage taken and damage dealt bonus against Undead.",
	"The Vermin Killer Job Trait will gain you a small amount of intimidation, damage taken and damage dealt bonus against Vermin.",
	"The Beastmen Killer Job Trait is only available to a single NPC, Rongelouts N Distaud.",
	"Similar Job Traits gained from both Main and Sub Job will not stack with eachother, only the higher tier will take effect.",
	"Don't forget to spend your Sparks and Accolades before the Conquest reset on Sunday!",
	"Save all your macros and settings on the Character Select screen to save yourself the headache of having to rewrite them later.",
	"Did you remember to get your Moglophone, Mystical Canteen, or Ra'Kaznar Plate today?",
	"The `/blockaid on` command prevents players from outside of your alliance from acting upon you.",
	-- "",
}

defaults.pos = {}
defaults.pos.x = math.floor(windower.get_windower_settings().ui_x_res / 2)
defaults.pos.y = math.floor(windower.get_windower_settings().ui_y_res / 3) * 2

defaults.text = T{}
defaults.text.font = 'Arial' --Consolas
defaults.text.size = 12
defaults.text.alpha = 255

defaults.flags = T{}
defaults.flags.bold = false
defaults.flags.draggable = true

defaults.options = {}
defaults.options.after_zone_fade_delay = 4
defaults.options.fade_multiplier = 2
defaults.options.random_number_buffer = 50

local recent_facts = T{}

settings = config.load(defaults)

player = windower.ffxi.get_player()

-- Create the VanaFacts text object
local VanaFacts = texts.new()
VanaFacts:alpha(settings.text.alpha)
VanaFacts:bold(settings.flags.bold)
VanaFacts:font(settings.text.font)
VanaFacts:pos(settings.pos.x,settings.pos.y)
VanaFacts:size(settings.text.size)
VanaFacts:draggable(settings.flags.draggable)

local Zoning = false
local fading = false
local fade_num = settings.text.alpha
local last_fact = 0

local add_to_chat = windower.add_to_chat

local function showFact(repeat_fact)

	local function getRandomFact()

		if repeat_fact then
			return settings.facts[last_fact]
		end

        local randomIndex
        repeat
            randomIndex = math.random(1, #settings.facts)
        until not recent_facts:contains(randomIndex)
		
        --Add the new randomIndex to recent_facts
        table.insert(recent_facts, randomIndex)
		
        --Ensure recent_facts does not exceed the buffer limit
        if #recent_facts > settings.options.random_number_buffer then
            table.remove(recent_facts, 1)
        end

		last_fact = randomIndex
		return settings.facts[randomIndex]
	end
	local fact = getRandomFact()
	local x = settings.pos.x
	local y = settings.pos.y
	VanaFacts:text(fact)
	VanaFacts:pos(x,y)
	VanaFacts:show()
	VanaFacts:alpha(0)
	coroutine.schedule(function()
		local fact_width = VanaFacts:extents()
		local x = settings.pos.x - (fact_width / 2)
		local y = settings.pos.y
		VanaFacts:pos(x,y)
		VanaFacts:alpha(settings.text.alpha)
	end, 0.1)
end

local function hideFact()
	VanaFacts:hide()
end

windower.register_event('prerender', function()

	local pos = windower.ffxi.get_position()
	local logged_in = windower.ffxi.get_info().logged_in

	--Zoning: Show a fact
	if pos == "(?-?)" and logged_in and not zoning then
		zoning = true
			showFact()

	--Unzone: wait a delay then trigger the fade
	elseif pos ~= "(?-?)" and zoning then
		zoning = false
		coroutine.schedule(function()
			fading = true
		end, settings.options.after_zone_fade_delay)
	end

	--Fade away
	if fading then
		if fade_num > settings.options.fade_multiplier then
			fade_num = fade_num - settings.options.fade_multiplier
			VanaFacts:alpha(fade_num)
			VanaFacts:bg_alpha(fade_num)
		else
			hideFact()
			fading = false
			fade_num = settings.text.alpha
			VanaFacts:alpha(fade_num)
			VanaFacts:bg_alpha(fade_num)
		end
	end

end)

windower.register_event('addon command',function(addcmd)
	if addcmd == 'repeat' or addcmd == 'r' then
		if last_fact == 0 then
			add_to_chat(8,('[VanaFacts] '):color(220)..('No facts have been displayed yet.'):color(8))
		else
			local repeat_fact = true
			showFact(repeat_fact)
			coroutine.schedule(function()
				fading = true
			end, settings.options.after_zone_fade_delay+1)
		end
	else
		local prefix = "//vanafacts, //vf"
		add_to_chat(8,('[VanaFacts] ':color(220))..('Version '):color(8)..(_addon.version):color(220)..(' by '):color(8)..(_addon.author):color(220)..(' ('):color(8)..(prefix):color(1)..(')'):color(8))
		add_to_chat(8,(' Command'):color(36)..(' - Description'):color(8))
		add_to_chat(8,' ')
		add_to_chat(8,(' repeat/r'):color(36)..(' - Repeat the last Fact displayed.'):color(8))
	end
end)
